/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scheduler;
import java.io.IOException;
import java.util.ArrayList;
import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testAppOnInput1() throws IOException{
        Parser parser = new Parser();

        testParserHelperFunctions(parser);

        try{
            
            parser.parseFile("sample_input.txt");

            Problem problem = parser.getProblem();

            testSample1(problem);

        }catch(IOException exception){
            throw(exception);
        }
    }

    public static void testParserHelperFunctions(Parser parser){


    }

    public static void testSample1(Problem problem){

        ArrayList<Slot> courseSlots = problem.getCourseSlots();

        ArrayList<Slot> labSlots = problem.getLabSlots();

        ArrayList<Course> courses = problem.getCourses();

        ArrayList<Lab> labs = problem.getLabs();
/*
        assertEquals("Number of course slots: ", 3, courseSlots.size());

        testSlot(courseSlots.get(0), "MO", "8:00", 3,2);
        testSlot(courseSlots.get(1), "MO", "9:00", 3,2);
        testSlot(courseSlots.get(2), "TU", "9:30", 2,1);

        assertEquals("Number of lab slots: ", 3, labSlots.size());

        testSlot(labSlots.get(0), "MO", "8:00", 4, 2); 
        testSlot(labSlots.get(1), "TU", "10:00", 2, 1); 
        testSlot(labSlots.get(2), "FR", "10:00", 2, 1); 

        assertEquals("Number of courses: ", 4, courses.size());

        testCourse(courses.get(0),"CPSC","433","LEC","01");
        testCourse(courses.get(1), "CPSC", "433", "LEC", "02");
        testCourse(courses.get(2), "SENG", "311", "LEC", "01");
        testCourse(courses.get(3), "CPSC", "567", "LEC", "01");

        assertEquals("Number of labs: ", 4, labs.size());

        testLab(labs.get(0), "CPSC", "433", "LEC", "01", "TUT", "01");
        testLab(labs.get(1), "CPSC", "433", "LEC", "02", "LAB", "02");
        testLab(labs.get(2), "SENG", "311", "LEC", "01", "TUT", "01");
        testLab(labs.get(3), "CPSC", "567", null , null, "TUT", "01");
        */

    }

    /*
    public static void testSlot(Slot slot, String day, String startTime, Integer courseMax, Integer courseMin){
        
        assertEquals("day: ", day, slot.getDay());
        assertEquals("start time: ", startTime, slot.getStartTime());
        assertEquals("course max: ", courseMax, slot.getCourseMax());
        assertEquals("course min: ", courseMin, slot.getCourseMin());
        
    }



    public static void testCourse(Course course, String courseName, String courseNumber, String courseFromat, String section){

        assertEquals("course name", courseName, course.getCourseName());
        assertEquals("course number", courseNumber, course.getCourseNumber());
        assertEquals("course format", courseFromat, course.getFormat());
        assertEquals("course section", section, course.getSection());
    }

    public static void testLab(Lab lab, String courseIdentifier , String courseFormat, String courseSection, String labFormat, String labSection){
        assertEquals("Course name: ", courseIdentifier, lab.getCourseName());
        assertEquals("course format: ", courseFormat, lab.getCourseFormat());
        assertEquals("course section: ", courseSection, lab.getCourseSection());
        assertEquals("lab section: ", labSection, lab.getLabSection());
    }
    */


}
