/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scheduler;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {

        Parser parser = new Parser();

        parser.parseFile(args[0]);

        OTree otree = new OTree(parser.getProblem());

        otree.traverseTree();
    }

}
